#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : giflib
Version  : 5.2.1
Release  : 1
URL      : https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz
Source0  : https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: giflib-license = %{version}-%{release}

%description
= GIFLIB =
Latest versions of GIFLIB are currently hosted at:
http://sourceforge.net/projects/giflib

%package license
Summary: license components for the giflib package.
Group: Default

%description license
license components for the giflib package.


%prep
%setup -q -n giflib-5.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570000678
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1570000678
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/giflib
cp COPYING %{buildroot}/usr/share/package-licenses/giflib/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/giflib/COPYING
